
export const SET_COUNTRIES_DATA = 'SET_COUNTRIES_DATA';
export const SET_SELECTED_COUNTRY_INDEX = 'SET_SELECTED_COUNTRY_INDEX';

export const SET_SETTING_DATA = 'SET_SETTING_DATA';
export const WORLD_MAP_TOGGLE_IS_CIRCLES_SHOW = 'WORLD_MAP_TOGGLE_IS_CIRCLES_SHOW';
export const WORLD_MAP_TOGGLE_IS_AUTO_FOCUS = 'WORLD_MAP_TOGGLE_IS_AUTO_FOCUS';